### ISSUE TITLE
Can't place player in world

### ISSUE THREAD

**Issue by Wamens** [Patbox/StyledChat#16]
[19:37:46] [Server thread/ERROR]: Couldn't place player in world
java.lang.ClassCastException: class net.minecraft.class_2585 cannot be cast to class net.minecraft.class_2588 (net.minecraft.class_2585 and net.minecraft.class_2588 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1761e840)
        at net.minecraft.class_3324.modify$zin000$styledChat_updatePlayerNameAfterMessage(class_3324.java:3973) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:212) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:130) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:117) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3248.redirect$zci000$handlePlayerJoin(class_3248.java:563) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3248.method_18785(class_3248.java:67) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:234) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[intermediary-server-1.18.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server-1.18.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[19:37:46] [Server thread/INFO]: Wamens lost connection: Invalid player data
[19:37:46] [Server thread/INFO]: Wamens left the game

**Comment by Patbox** [comment]
Huh? Whatdo you mean by `Can't place player in world` you can't join? Which version do you use?

**Comment by Wamens** [comment]
Yeah can't join, and using version 1.2.2+1.18

**Comment by Wamens** [comment]
Any updates on this?

**Comment by Wamens** [comment]
Found out what it was. was another plugin interfering with it
