### ISSUE TITLE
Chain link failed, continuing to next one

### ISSUE THREAD

**Issue by TheAIguy-dev** [Patbox/StyledChat#49]
When trying to send a message, I get this error:
```
[19:04:22 INFO] [Server thread]: [DedicatedServer] <TheAIguy_> asd
[19:04:22 ERROR] [Server thread]: [FutureChain] Chain link failed, continuing to next one
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.getString()" because the return value of "net.minecraft.class_7604.comp_1081()" is null
	at net.minecraft.server.level.ServerPlayer.handler$cck000$chat-control$onBroadcastChatMessage(ServerPlayer.java:6344) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.sendChatMessage(ServerPlayer.java) ~[?:?]
	at net.minecraft.server.players.PlayerList.broadcastChatMessage(PlayerList.java:835) ~[?:?]
	at net.minecraft.server.players.PlayerList.broadcastChatMessage(PlayerList.java:823) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:1429) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$8(ServerGamePacketListenerImpl.java:1303) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:10818) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:115) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zjl000$carpet$modifiedRunLoop(MinecraftServer.java:12451) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```
1.20.1 fabric server, mod version 2.2.3

**Comment by TheAIguy-dev** [comment]
It appears that this error only occurs when the message doesn't have any formatting. By adding `<reset>` anywhere in the message it just works.
First message is `test`, second is `<reset>test`.
```
[19:39:48 INFO] [Server thread]: [DedicatedServer]  [⛏] TheAIguy_: test
[19:39:48 ERROR] [Server thread]: [FutureChain] Chain link failed, continuing to next one
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2561.getString()" because the return value of "net.minecraft.class_7604.comp_1081()" is null
	at net.minecraft.server.level.ServerPlayer.handler$cck000$chat-control$onBroadcastChatMessage(ServerPlayer.java:6344) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.sendChatMessage(ServerPlayer.java) ~[?:?]
	at net.minecraft.server.players.PlayerList.broadcastChatMessage(PlayerList.java:835) ~[?:?]
	at net.minecraft.server.players.PlayerList.broadcastChatMessage(PlayerList.java:823) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.java:1429) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$8(ServerGamePacketListenerImpl.java:1303) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:10818) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:743) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zjl000$carpet$modifiedRunLoop(MinecraftServer.java:12451) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[19:39:53 INFO] [Server thread]: [DedicatedServer]  [⛏] TheAIguy_: test
```

**Comment by TheAIguy-dev** [comment]
Using any emoticon also lets the message through.
Also, `shrug` should have 4 backslashes by default.
