### ISSUE TITLE
Compatability issue with Fuji

### ISSUE THREAD

**Issue by fucksophie** [Patbox/StyledChat#54]
This happens even when the chat module in [Fuji](https://modrinth.com/mod/fuji) is disabled.
```
[12:18:37] [Server thread/INFO]: yxguden[/<>:46892] logged in with entity id 14 at (178.77333698113645, 68.0, -59.32733537851118)
[12:18:37] [Server thread/ERROR]: Couldn't place player in world
java.lang.ClassCastException: class net.minecraft.class_8828$class_2585 cannot be cast to class net.minecraft.class_2588 (net.minecraft.class_8828$class_2585 and net.minecraft.class_2588 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3c756e4d)
        at net.minecraft.class_3324.modify$bdj000$styledchat$styledChat_updatePlayerNameAfterMessage(class_3324.java:7024) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:221) ~[server-intermediary.jar:?]
        at net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
        at net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
        ````

**Comment by sakurawald** [comment]
It's an issue about fuji, the module loader loads the class unexpectedly. I will see what is happening here.

**Comment by sakurawald** [comment]
> It's an issue about fuji, the module loader loads the class unexpectedly. I will see what is happening here.

It's not about the 'chat' module conflicts, but the 'system_message' module. I will fix it later.

**Comment by sakurawald** [comment]
> > It's an issue about fuji, the module loader loads the class unexpectedly. I will see what is happening here.
> 
> It's not about the 'chat' module conflicts, but the 'system_message' module. I will fix it later.

The problem is, the module 'system_message" hijacks the translatable key "multiplayer.player.joined", and consume the TranslatableTextContent type, return a PlainTextContent for sendBroadcast() function.

The relevant code is: https://github.com/Patbox/StyledChat/blob/31d653dc26c9dd69bf30557f82c1cb5562f371f4/src/main/java/eu/pb4/styledchat/mixin/PlayerManagerMixin.java#L53

In vanilla minecraft, the sendBroadcast() in onPlayerConnect() should always expected to accept a TranslatableTextContent argument.

**Comment by sakurawald** [comment]
Fuji has removed the possible conflicting keys in the generated default language file, and also document the issue in its wiki. I think this issue can be closed.
