### ISSUE TITLE
Disconnect upon joining a world in 1.21.2/3

### ISSUE THREAD

**Issue by nekoblitz** [Patbox/StyledChat#57]
In 1.21.2, [bug MC-274960](https://bugs.mojang.com/browse/MC-274960) was patched, disallowing duplicate registry entries. This seems be causing a disconnect if using the mod in those versions:

```
[22:55:03] [Render thread/ERROR]: Failed to handle packet net.minecraft.class_8733@7e716732, disconnecting
net.minecraft.class_148: Network Registry Load
	at knot/net.minecraft.class_9173.method_62155(class_9173.java:99) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9173.method_56585(class_9173.java:146) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8674.method_57043(class_8674.java:117) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8674.method_57044(class_8674.java:109) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8674.method_52794(class_8674.java:117) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8733.method_53041(class_8733.java:22) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_8733.method_11054(class_8733.java:8) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2600.method_11072(class_2600.java:27) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:164) [client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:138) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:123) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1307) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:933) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
Caused by: java.lang.IllegalStateException: Adding duplicate key 'ResourceKey[minecraft:chat_type / styled_chat:generic_hack]' to registry
	at knot/net.minecraft.class_2370.method_10272(class_2370.java:107) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_2378.method_39197(class_2378.java:126) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7655.handler$chg000$styledchat$styledChat$injectMessageTypes(class_7655.java:2026) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7655.method_45121(class_7655.java:185) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_7655.method_56519(class_7655.java:176) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_9173.method_62155(class_9173.java:95) ~[client-intermediary.jar:?]
	... 17 more
```
The full log is attached below.
[latest.log](https://github.com/user-attachments/files/17669962/latest.log)

**Comment by cecaelion** [comment]
I am having the same problem in 1.21.3.
